


products_map = {
    "Kash Reserv" : "DidiRahmenkredit",
    "ROBIN" : "DidiVermögen",
    "VR-FinanzPlan" : "DidiVermögen",
    "NIBCard" : "DidiCard",
    "SpardaSecure" : "DidiSecure",
    "Sparkassen-Card" : "DidiCard",
    "RaboSpar90" : "DidiSuperSparkonto",
    "RaboSpar30" : "DidiSparkonto",
    "Kash Borgen" : "DidiRatenkredit",
    "DispoEasy" : "DidiDispo",
    "maxblue" : "DidiInvestor",
    "SpardaNet" : "DidiOnline",
    "S-Card" : "DidiCard",
    "SparkassenCard": "DidiCard",

    "Kleeblatt" : "Didi",
    "sparSmart" : "DidiSuperSparKonto",
    "TWINT" : "DidiPay",
    "easyKonto" :"DidiEasy",
    "SpardaApp" : "DidiApp",
    "EB-Banking App": "DidiApp",
    "Fleks Horten" : "DidiTagesgeld",
    "Anadi-Konto" : "DidiKonto",
    "CrontoPush" : "DidiLogin",
    "VRNetKey" : "DidiLogin",
    "boon." : "DidiPay",
    "Anadi mobilePAY" :  "DidiApp",
    "ZOIN" : "DidiPay",
    "MLP-Konto" : "DidiKonto",
    "S-direkt" : "DidiInvestor",
    "S-Depot" : "DidiVermögen",
    "S-Broker" : "DidiBroker",
    "SPG-Verein" : "DidiVerein",

    "S-Tagesgeld" : "DidiTagesgeld",
    "meine.deutsche-bank.de" : "DidiApp",
    "netsp@r_konto" : "DidiSparKonto",
    "SpardaMobil-Banking" : "DidiApp",
    "VERIMI" : "DidiLogin",
    "SIX Paynet AG" : "DidiPay",
    "PostFinance AG" : "DidiEasy",
    "CrontoSign Swiss App": "DidiApp",
    "Vostar-Account" : "DidiKonto",
    "\"Vostar\"-App" : "DidiApp",
    "Vostar-App": "DidiApp",
    "VR-ProfiBroker" : "DidiVermögen",
    "VR-BankingApp" : "DidiApp",
    "VR-NetWorld-Card" : "DidiLoginCard",
    "Sparkassen-Card" : "DidiCard",
    "SparkassenShop" : "DidiShop",
    "Sparkassen-App": "DidiApp",
    "KWITT" : "DidiPay",
    "Kwitt": "DidiPay",
    "S-pushTAN-App" : "pushTAN-App",
    "MeinRahmenKredit" : "DidiRahmenKredit",
    "MeinWohnKredit" : "DidiWohnKredit",
    "MeinWunschKredit" : "DidiKredit",
    "Prepaid Trios" : "DidiKonto",
    "KEYPLAN-Konto" : "DidiKonto",
    "EvoRepair" : "DidiRepair",
    "CASH26" : "DidiCash",
    "NetBanking Plus" : "DidiOnline",
    "auxmoney" : "DidiKredit",
    "OYAK-Keys" : "DidiLogin",
     "\"Deutsche Bank Mobile\"-App" : "DidiApp",
    "KEYPLAN" : "DidiBroker"
}